name: riverpod_test
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging:
  riverpod:

dev_dependencies:
  pedantic:
  lint:
  test:
  #test_coverage:
  coverage:
  test_cov: